import 'package:hive_flutter/hive_flutter.dart';
import '../../features/daily_activities/models/event.dart';
import '../../features/notes/models/note.dart';
import '../models/rating.dart';

class HiveService {
  static const String _eventsBoxName = 'events';
  static const String _transactionsBoxName = 'transactions';
  static const String _notesBoxName = 'notes';
  static const String _ratingsBoxName = 'ratings';

  static bool _isInitialized = false;
  static bool get isInitialized => _isInitialized;
  static String? _currentUserId;

  // Get user-specific box names
  static String _getUserBoxName(String baseName, String? userId) {
    if (userId == null || userId.isEmpty) {
      return '${baseName}_anonymous';
    }
    return '${baseName}_$userId';
  }

  static Future<void> init([String? userId]) async {
    await Hive.initFlutter();

    _currentUserId = userId;

    // Register adapters (generated by build_runner) with safety checks
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(EventAdapter());
    }
    if (!Hive.isAdapterRegistered(8)) {
      Hive.registerAdapter(EventStatusAdapter());
    }

    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(NoteAdapter());
    }
    if (!Hive.isAdapterRegistered(9)) {
      Hive.registerAdapter(NoteStatusAdapter());
    }
   
    if (!Hive.isAdapterRegistered(6)) {
      Hive.registerAdapter(RatingAdapter());
    }
    if (!Hive.isAdapterRegistered(11)) {
      Hive.registerAdapter(RatingValueAdapter());
    }
    if (!Hive.isAdapterRegistered(12)) {
      Hive.registerAdapter(ItemTypeAdapter());
    }

    // Open user-specific boxes (create if they don't exist)
    try {
      print('Opening Hive boxes for user: ${userId ?? "anonymous"}...');
      await openUserBoxes(userId);
      print('All Hive boxes opened successfully');
      _isInitialized = true;
    } catch (e) {
      print('Error opening Hive boxes: $e');
      // If there's a corruption error, we could handle it here
      // but for now, just rethrow
      rethrow;
    }
  }

  static Future<void> openUserBoxes(String? userId) async {
    // Close existing boxes if open
    await _closeCurrentBoxes();

    _currentUserId = userId;

    final eventsBoxName = _getUserBoxName(_eventsBoxName, userId);

    final notesBoxName = _getUserBoxName(_notesBoxName, userId);
   
    final ratingsBoxName = _getUserBoxName(_ratingsBoxName, userId);

    await Hive.openBox<Event>(eventsBoxName);
    await Hive.openBox<Note>(notesBoxName);
   
    await Hive.openBox<Rating>(ratingsBoxName);
  }

  static Future<void> _closeCurrentBoxes() async {
    try {
      // Close all possible user-specific boxes
      final currentEventsBox = _getUserBoxName(_eventsBoxName, _currentUserId);
      final currentTransactionsBox = _getUserBoxName(
        _transactionsBoxName,
        _currentUserId,
      );
      final currentNotesBox = _getUserBoxName(_notesBoxName, _currentUserId);
   
      final currentRatingsBox = _getUserBoxName(
        _ratingsBoxName,
        _currentUserId,
      );

      if (Hive.isBoxOpen(currentEventsBox)) {
        await Hive.box<Event>(currentEventsBox).close();
      }

      if (Hive.isBoxOpen(currentNotesBox)) {
        await Hive.box<Note>(currentNotesBox).close();
      }
    
      if (Hive.isBoxOpen(currentRatingsBox)) {
        await Hive.box<Rating>(currentRatingsBox).close();
      }
    } catch (e) {
      print('Error closing boxes: $e');
    }
  }

  static Box<Event> get eventsBox {
    final boxName = _getUserBoxName(_eventsBoxName, _currentUserId);
    return Hive.box<Event>(boxName);
  }

  // Notes
  static Box<Note> get notesBox {
    final boxName = _getUserBoxName(_notesBoxName, _currentUserId);
    return Hive.box<Note>(boxName);
  }

  
  // Ratings
  static Box<Rating> get ratingsBox {
    final boxName = _getUserBoxName(_ratingsBoxName, _currentUserId);
    return Hive.box<Rating>(boxName);
  }

  static Future<void> clearAllData() async {
    await eventsBox.clear();
    await notesBox.clear();
  
    await ratingsBox.clear();
  }

  // Clear data for a specific user (used when switching accounts)
  static Future<void> clearUserData(String? userId) async {
    try {
      final eventsBoxName = _getUserBoxName(_eventsBoxName, userId);
      final transactionsBoxName = _getUserBoxName(_transactionsBoxName, userId);
      final notesBoxName = _getUserBoxName(_notesBoxName, userId);
    
      final ratingsBoxName = _getUserBoxName(_ratingsBoxName, userId);

      // Clear the boxes if they exist
      if (Hive.isBoxOpen(eventsBoxName)) {
        await Hive.box<Event>(eventsBoxName).clear();
      }
      if (Hive.isBoxOpen(notesBoxName)) {
        await Hive.box<Note>(notesBoxName).clear();
      }
     
      if (Hive.isBoxOpen(ratingsBoxName)) {
        await Hive.box<Rating>(ratingsBoxName).clear();
      }

      print('Cleared all local data for user: ${userId ?? "anonymous"}');
    } catch (e) {
      print('Error clearing user data: $e');
    }
  }

  // Switch to a different user's data
  static Future<void> switchUser(String? newUserId) async {
    print(
      'Switching from user ${_currentUserId ?? "anonymous"} to ${newUserId ?? "anonymous"}',
    );
    await openUserBoxes(newUserId);
  }

  // Method to completely reset Hive data (for debugging/reset purposes)
  static Future<void> resetAllData() async {
    try {
      // Close boxes first
      if (Hive.isBoxOpen(_eventsBoxName)) {
        await Hive.box<Event>(_eventsBoxName).close();
      }

      if (Hive.isBoxOpen(_notesBoxName)) {
        await Hive.box<Note>(_notesBoxName).close();
      }
     
      // Delete all boxes to clear corrupted data
      await Hive.deleteBoxFromDisk(_eventsBoxName);
      await Hive.deleteBoxFromDisk(_transactionsBoxName);
      await Hive.deleteBoxFromDisk(_notesBoxName);

      await Hive.deleteBoxFromDisk(_ratingsBoxName);

      // Reopen boxes
      await Hive.openBox<Event>(_eventsBoxName);
      await Hive.openBox<Note>(_notesBoxName);
    
    } catch (e) {
      print('Error resetting Hive data: $e');
    }
  }

  static Future<void> dispose() async {
    await Hive.close();
  }
}
