// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To get your API keys:
/// 1. Go to Firebase Console: https://console.firebase.google.com/
/// 2. Select your project (app039-93c95)
/// 3. Go to Project Settings > General
/// 4. Scroll down to "Your apps" section
/// 5. For each platform, click the config icon and copy the values
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Get from Firebase Console > Web app config
    appId: 'YOUR_WEB_APP_ID', // Get from Firebase Console > Web app config
    messagingSenderId: '113748906506588593629',
    projectId: 'app039-93c95',
    authDomain: 'app039-93c95.firebaseapp.com',
    storageBucket: 'app039-93c95.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID', // Optional, get from Firebase Console
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwW4WNUvU54q3096Ked_iLAt4ZIzOHGJo',
    appId: '1:310047978101:android:911fa48b3ade6801307e3c',
    messagingSenderId: '310047978101',
    projectId: 'app039-93c95',
    storageBucket: 'app039-93c95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWonA6HL0ktmVMXu-nfqK5h5kqHEWXZI',
    appId: '1:310047978101:ios:841ee56349a279d8307e3c',
    messagingSenderId: '310047978101',
    projectId: 'app039-93c95',
    storageBucket: 'app039-93c95.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'YOUR_MACOS_API_KEY', // Get from Firebase Console > macOS app config
    appId: 'YOUR_MACOS_APP_ID', // Get from Firebase Console > macOS app config
    messagingSenderId: '113748906506588593629',
    projectId: 'app039-93c95',
    storageBucket: 'app039-93c95.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:
        'YOUR_WINDOWS_API_KEY', // Get from Firebase Console > Windows app config
    appId:
        'YOUR_WINDOWS_APP_ID', // Get from Firebase Console > Windows app config
    messagingSenderId: '113748906506588593629',
    projectId: 'app039-93c95',
    storageBucket: 'app039-93c95.appspot.com',
  );
}
